---
- hosts: webserver
  become: yes
  tasks:
  - name: update packages
    apt:
      update_cache: yes
  - name: install appche
    apt:
      name: apache2
      state: present
  - name: create the home page
    file:
      path: /home/ansible/index.html
      state: file
  - name: stop apache
    service:
      name: apache2
      state: stopped
  - name: copy the home page to server
    file:
      src: /home/ansible/index.html
      dest: /var/www/html/index.html
  - name: start apache
    service:
      name: apache2
      state: started



