---
- hosts: webserver
  become: yes
  tasks:
  - name: update packages
    apt:
      update_cache: yes
  - name: install appche
    apt:
      name: apache2
      state: present
    notify:
    - Restart Apache
  - name: create the home page
    copy:
      dest: /var/www/index/index.html
      content: "<h1> welcome to apache (controlled by anible) </h1>"  
    notify: 
    - Restart Apache
  handlers:    
  - name: Restart Apache
    service:
      name: apache2
      state: restarted
      



